blank_issues_enabled: false
contact_links:
    - name: Q & A
      url: https://github.com/gitkraken/vscode-gitlens/discussions?discussions_q=category%3AQ%26A
      about: Ask and answer questions about GitLens
    - name: Documentation
      url: https://help.gitkraken.com/gitlens
      about: Read the GitLens support documentation
    - name: GitKraken Support
      url: https://help.gitkraken.com/gitlens/gl-contact-support/?product_s_=GitLens
      about: Get email support for issues and questions on paid features or relating to your GitKraken account or plan
